{% set name = "py-popgen" %}
{% set version = "0.1.13" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"

requirements:
  host:
    - cython
    - pip
    - python
  run:
    - python
    - biopython >=1.74
    - matplotlib
    - pandas
    - pybedtools
    - pysam
    - scikit-learn
    - bcftools >=1.9
    - vcftools
    - admixture
    - admixtools
    - plink
    - shapeit
    - tabix
    - r-base
    - rpy2
    - r-devtools
    - r-bh
    - r-clipr
    - r-digest
    - r-dplyr
    - r-ellipsis
    - r-hms
    - r-pillar
    - r-plogr
    - r-rcpp
    - r-readr
    - r-stringi
    - r-stringr
    - r-tidyr
    - r-tidyselect
    - r-zeallot

test:
  imports:
    - pgpipe

about:
  home: "https://ppp.csusm.edu/"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "Software platform for facilitating population genomic analyses"
  doc_url: "https://ppp.readthedocs.io"
  dev_url: "https://github.com/jaredgk/PPP/"

extra:
  recipe-maintainers:
    - aewebb80
    - jaredgk
