args<-commandArgs(trailingOnly=TRUE)
t0<-read.table(args[1],header=F)
q0<-read.table(args[2],header=F)
#names(t0)
#names(q0)
#filename<-paste(args[3],".pdf")
pdf(args[3])
plot(t0$V2,t0$V3,type="l",xlab="Divergence times (t0)",ylab="Frequency")
plot(q0$V2,q0$V3,type="l",xlab="Population size (q0)",ylab="Frequency")
plot(q0$V4,q0$V5,type="l",xlab="Population size (q1)",ylab="Frequency")
plot(q0$V6,q0$V7,type="l",xlab="Population size (q2)",ylab="Frequency")
plot(q0$V8,q0$V9,type="l",xlab="Migration rate (m0->1)",ylab="Frequency")
plot(q0$V10,q0$V11,type="l",xlab="Migration rate (m1->0)",ylab="Frequency")
dev.off()
